name: Deploy web via Fly

on:
  workflow_dispatch

jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            # - uses: superfly/flyctl-actions/setup-flyctl@master
            - name: Install flyctl
              run: curl -L https://fly.io/install.sh | sh
            - run: flyctl deploy --remote-only
              env:
                FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
