name: Deploy web via Fly

on:
  workflow_dispatch

jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install flyctl
              run: |
                curl -L https://fly.io/install.sh | bash
                echo "$HOME/.fly/bin" >> $GITHUB_PATH
            - name: Deploy
              run: fly deploy --remote-only
              env:
                FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
