name: Deploy web

on:
  workflow_dispatch

jobs:
    Deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: 1
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                ruby-version: 3.3
                bundler-cache: true
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Set up Kamal
              run: gem install kamal
            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: ghcr.io/${{ github.repository }}-web:latest
            - name: Kamal setup
              run: kamal setup
              env:
                KAMAL_REGISTRY_USERNAME: ${{ github.actor }}
                KAMAL_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
