name: Publish Package to npmjs

on:
  workflow_dispatch
  # release:
    # types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - name: Publish
        run: npm publish --dry-run --provenance --access public
        working-directory: ./packages/create-kotekan
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
